# Generated by Django 4.0.3 on 2023-03-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
