# Generated by Django 4.0.3 on 2023-03-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_automobilevo_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='vin',
        ),
    ]
